CREATE PROCEDURE [dbo].[COMPANY_ORDERS_GET]
	@companyId bigint = 0
AS
	SELECT 
		o.ORDER_ID,
		o.ORDER_DESCRIPTION,
		c.COMPANY_ID,
		c.COMPANY_NAME,
		c.COMPANY_DESCRIPTION
	FROM 
		COMPANY c (NOLOCK)
	JOIN COMPANY_ORDERS o (NOLOCK) ON c.COMPANY_ID = o.COMPANY_ID
	WHERE
		(c.COMPANY_ID = @companyId OR @companyId = 0)
RETURN 0
