CREATE PROCEDURE [dbo].[ORDER_PRODUCTS_GET]
	@orderId bigint = 0
AS
	SELECT
		op.QUANTITY,
		p.PRODUCT_ID,
		op.PRICE,
		p.PRODUCT_NAME, 
		p.PRODUCT_DESCRIPTION
	FROM 
		ORDER_PRODUCT op (NOLOCK) 
	JOIN PRODUCT p (NOLOCK) ON op.PRODUCT_ID = p.PRODUCT_ID
	WHERE 
		(op.ORDER_ID = @orderId OR @orderId = 0)
RETURN 0
