DECLARE @id bigint;

-- companies
SET IDENTITY_INSERT Company ON

INSERT INTO Company (COMPANY_ID, COMPANY_NAME, COMPANY_DESCRIPTION) VALUES (1,'BrainWare Company', 'Yesterdays tomorrow is the future')

SET IDENTITY_INSERT Company OFF

-- products
SET IDENTITY_INSERT Product ON

INSERT INTO Product (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES (1,'Pipe fitting',1.23)
INSERT INTO Product (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES (2,'10" straight',2.00)
INSERT INTO Product (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES (3,'Quarter turn',0.75)
INSERT INTO Product (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES (4,'5" straight',1.1)
INSERT INTO Product (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES (5,'2" stright',0.90)

SET IDENTITY_INSERT Product OFF

-- orders
INSERT INTO COMPANY_ORDERS VALUES ('Our first order.', 1)

SET @id = SCOPE_IDENTITY()
INSERT INTO ORDER_PRODUCT VALUES (@id, 1, 1.23, 10)
INSERT INTO ORDER_PRODUCT VALUES (@id, 3, 1.00, 3)
INSERT INTO ORDER_PRODUCT VALUES (@id, 4, 1.1, 22)

INSERT INTO COMPANY_ORDERS VALUES ('Our Second order.', 1)

SET @id = SCOPE_IDENTITY()
INSERT INTO ORDER_PRODUCT VALUES (@id, 1, 1.23, 10)
INSERT INTO ORDER_PRODUCT VALUES (@id, 3, 1.00, 3)
INSERT INTO ORDER_PRODUCT VALUES (@id, 2, 2, 13)
INSERT INTO ORDER_PRODUCT VALUES (@id, 5, 0.9, 3)


INSERT INTO COMPANY_ORDERS VALUES ('Our third order.', 1)

SET @id = SCOPE_IDENTITY()
INSERT INTO ORDER_PRODUCT VALUES (@id, 1, 1.23, 10)
INSERT INTO ORDER_PRODUCT VALUES (@id, 2, 2.00, 7)
INSERT INTO ORDER_PRODUCT VALUES (@id, 3, 0.75, 13)
INSERT INTO ORDER_PRODUCT VALUES (@id, 4, 1.1, 5)
INSERT INTO ORDER_PRODUCT VALUES (@id, 5, 0.9, 3)



