CREATE TABLE [dbo].[COMPANY_ORDERS]
(
	[ORDER_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[ORDER_DESCRIPTION] NVARCHAR(1000) NOT NULL, 
    [COMPANY_ID] BIGINT NOT NULL, 
    CONSTRAINT [FK_order_to_company] FOREIGN KEY ([COMPANY_ID]) REFERENCES [COMPANY]([COMPANY_ID]),
)
