CREATE TABLE [dbo].[ERROR_LOG]
(
	[ERROR_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY, 
    [MESSAGE] VARCHAR(MAX) NULL, 
    [STACKTRACE] VARCHAR(MAX) NULL, 
    [SOURCE] VARCHAR(50) NULL, 
    [DATE] DATETIME NULL DEFAULT GETDATE(), 
    [ERROR_LEVEL] VARCHAR(50) NULL
)
