CREATE TABLE [dbo].[ORDER_PRODUCT]
(
	[ORDER_ID] BIGINT NOT NULL,
	[PRODUCT_ID] BIGINT NOT NULL,
	[PRICE] DECIMAL(18, 2) NOT NULL, 
	[QUANTITY] int NOT NULL, 
    CONSTRAINT [PK_orderproduct] PRIMARY KEY ([ORDER_ID], [PRODUCT_ID]), 
    CONSTRAINT [FK_orderproduct_product] FOREIGN KEY ([PRODUCT_ID]) REFERENCES [PRODUCT]([PRODUCT_ID]), 
    CONSTRAINT [FK_orderproduct_order] FOREIGN KEY ([ORDER_ID]) REFERENCES [COMPANY_ORDERS]([ORDER_ID])
)
