CREATE TABLE [dbo].[PRODUCT]
(
	[PRODUCT_ID] BIGINT NOT NULL PRIMARY KEY IDENTITY,
	[PRODUCT_NAME] NVARCHAR(128) NOT NULL, 
    [PRICE] DECIMAL(18, 2) NOT NULL, 
    [PRODUCT_DESCRIPTION] NCHAR(1000) NULL,

)
